<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Receipt #REC-<?= str_pad($payment->id, 4, '0', STR_PAD_LEFT) ?></title>
    
    <?= $this->Html->css('receipt') ?>
</head>
<body>

    <div class="system-header">
        Generated by System Administrator: MUHAMMAD YASIN BIN AZMAN
    </div>

    <div class="receipt-container">
        <div class="header">
            <div class="brand">
                <h1>SF Car Rental</h1>
                <p>123 Business Avenue, Shah Alam<br>Selangor, Malaysia<br>Contact: +60 12-345 6789</p>
            </div>
            <div class="receipt-details" style="text-align: right;">
                <h2>Official Receipt</h2>
                <p>#REC-<?= str_pad($payment->id, 4, '0', STR_PAD_LEFT) ?></p>
                <p style="font-weight: normal; color: #666;">Date: <?= h($payment->created->format('d M Y, h:i A')) ?></p>
            </div>
        </div>

        <div class="info-grid">
            <div class="info-box">
                <h4>Billed To</h4>
                <strong><?= h($payment->booking->customer->full_name ?? 'N/A') ?></strong><br>
                Phone: <?= h($payment->booking->customer->phone_number ?? 'N/A') ?><br>
                Booking Ref: #<?= h($payment->booking_id) ?>
            </div>
            <div class="info-box">
                <h4>Payment Information</h4>
                Status: <strong><?= h($payment->payment_status) ?></strong><br>
                Method: <?= h($payment->payment_method ?: 'N/A') ?><br>
                Paid On: <?= $payment->payment_time ? h($payment->payment_time->format('d M Y')) : '-' ?>
            </div>
        </div>

        <table class="receipt-table">
            <thead>
                <tr>
                    <th>Description</th>
                    <th style="text-align: center;">Days</th>
                    <th style="text-align: right;">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Car Rental Services<br>
                        <small style="color: #666;">Vehicle: <?= h($payment->booking->car->car_model ?? 'Vehicle Details') ?></small>
                    </td>
                    <td style="text-align: center;">-</td>
                    <td style="text-align: right;">RM <?= $this->Number->format($payment->total_payment, ['places' => 2]) ?></td>
                </tr>
                <tr class="total-row">
                    <td colspan="2" style="text-align: right; border-bottom: none;">Total Paid:</td>
                    <td style="text-align: right; border-bottom: none; color: #28a745;">RM <?= $this->Number->format($payment->total_payment, ['places' => 2]) ?></td>
                </tr>
            </tbody>
        </table>

        <div class="footer">
            <p>Thank you for choosing SF Car Rental. This is a computer-generated document. No signature is required.</p>
        </div>
    </div>

    <?= $this->Html->script('receipt') ?>
</body>
</html>